# Generated by Django 5.1.4 on 2025-01-17 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название поставщика', max_length=100, verbose_name='Поставщик')),
                ('email', models.EmailField(help_text='Адрес электронной почты поставщика', max_length=100, verbose_name='Электронная почта')),
                ('country', models.CharField(help_text='Страна поставщика', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(help_text='Город поставщика', max_length=100, verbose_name='Город')),
                ('street', models.CharField(help_text='Улица поставщика', max_length=100, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Номер дома поставщика', max_length=100, verbose_name='Номер дома')),
                ('level', models.ImageField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'Индивидуальный предприниматель')], help_text='Уровень поставщика', upload_to='', verbose_name='Уровень поставщика')),
                ('debt', models.DecimalField(decimal_places=2, help_text='Долг поставщика', max_digits=10, verbose_name='Долг')),
                ('create_time', models.DateTimeField(help_text='Дата создания поставщика', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название продукта', max_length=100, verbose_name='Название продукта')),
                ('model', models.CharField(help_text='Модель продукта', max_length=100, verbose_name='Модель')),
                ('date_release', models.DateField(help_text='Дата выпуска продукта', verbose_name='Дата выпуска')),
                ('supplier', models.ForeignKey(help_text='Поставщик продукта', on_delete=django.db.models.deletion.CASCADE, to='electronics_network.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
